### PR TITLE
feature: MSSQL suspicious behavior rules

### PR DESCRIPTION
**Pull request by 0xFFaraday**
This PR contains rules for the event ID '15457' for MSSQL. These rules have been highly successful in internal investigations where threat actors have exhibited this behavior. I hope anyone else utilizing chainsaw gets great value out of these rules! 

Screenshot below shows true positives of the rules firing:
Screenshot 2024-09-22 at 10 53 13 AM

Please let me know if I need to change anything with this PR. Thanks!

### CODE REVIEW

**Comment by FranticTyping** [comment]
Hey @0xFFaraday 

Thanks for raising this PR, I like the detection coverage these rules add. 
Before I merge the PR, can you make a couple of adjustments to the severity "level":

**Potential MSSQL Suspicious Activity**

Given that we're just looking at the Event ID and no other features, I think the severity should probably be Medium. 

**MSSQL XP_CMDSHELL Enabled**

I need to cleanup the existing rules in this repo, but moving forwards I want to reserve "Critical" severity level for rules that have almost no chance of *not* being malicious. E.g. mimikatz being detected on a domain controller. 

For this rule, while XP_CMDSHELL being enabled is definitely suspicious, I don't think it's always a firm indicator of malicious activity. Let's drop this one to a High.

**Comment by 0xFFaraday** [comment]
Hello @FranticTyping, I just updated the severties as requested!

**Comment by FranticTyping** [comment]
Merged! Thanks for contributing these rules ⭐

**Comment by 0xFFaraday** [comment]
Of course happy to increase the overall detection coverage, this tool has been amazing for mass-log parsing!

**Pull request merged**
